# Generated by Django 4.0.1 on 2024-03-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatScenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('socket_url', models.URLField(verbose_name='')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('number_of_messages', models.IntegerField(default=10)),
            ],
        ),
    ]
