# Generated by Django 4.0.1 on 2024-03-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatscenario',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='chat_scenarios/background'),
        ),
        migrations.AddField(
            model_name='chatscenario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_scenarios/image'),
        ),
        migrations.AlterField(
            model_name='chatscenario',
            name='number_of_messages',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='chatscenario',
            name='socket_url',
            field=models.CharField(max_length=1000, verbose_name='Socket URL'),
        ),
    ]
